import { Teejay, DrStrange, Timi, Slimany, Ifedimeji, Team1, Team2, Team3, Team4, Team5, Team6, Team7, Team8, Team9, Team11, Team12, Team13, Team14, Team15 } from "../assets";

export const navLinks = [
  { href: "/", label: "Home" },
  { href: "/about-us", label: "About Us" },
  { href: "/blog", label: "Blog" },
  { href: "/departmental-fees", label: "Departmental Fees" },
  { href: "/events", label: "Events" },
  { href: "/#contact-us", label: "Contact Us" },
];

export const teamMembers = [
  {
		name: "Tijani Saheed Olalekan",
		role: "Project Manager & Backend Developer",
		image: Teejay,
		team: "Tech",
		facebook: "https://web.facebook.com/profile.php?id=100059079370738",
		linkedin: "https://linkedin.com/in/saheed-tijani-b9935625b",
    twitter: "https://twitter.com/def_input_name",
    github: "https://github.com/TSOlami/",
    website: "https://tsolami.github.io/",
  },
  {
		name: "Ifedolalapo Omoniyi",
		role: "Frontend Developer & Web Designer",
		image: DrStrange,
		team: "Tech",
		facebook: "https://web.facebook.com/",
		linkedin: "https://www.linkedin.com/in/ifedolapo-omoniyi/",
    twitter: "https://twitter.com/ife_ifedolapo",
    github: "https://github.com",
    website: "https://ifedolapo.netlify.app/",
  },
  {
    name: "Abdulkareem Abdulqudus",
    role: "Software Engineer",
    image: Slimany,
    team: "Tech",
    facebook: "https://web.facebook.com/",
    linkedin: "https://www.linkedin.com/in/slimany/",
    twitter: "https://twitter.com/Slimany_",
    github: "https://github.com",
    website: "https://slimany.netlify.app/",
  },
  {
		name: "Timilehin Olusa",
		role: "Backend Developer",
		image: Timi,
		team: "Tech",
		facebook: "https://web.facebook.com/100016232149332/",
		linkedin: "https://www.linkedin.com/in/timilehin-olusa-781386250/",
    twitter: "https://twitter.com/TimmieOlusa",
    github: "https://github.com/DeepBrain07",
    website: "https://timilehinolusa.netlify.app/",
  },
  {
    name: "Ifedimeji Omoniyi",
    role: "Backend Developer",
    image: Ifedimeji,
    team: "Tech",
    facebook: "https://web.facebook.com/",
    linkedin: "https://www.linkedin.com",
    twitter: "https://twitter.com/ifedimeji_",
    github: "https://www.behance.net/Ifedimejiomoniyi",
    website: "https://ifedimeji.netlify.app/",
  },
  {
		name: "Oluwasegun Abraham Ajeolu",
		role: "President",
		image: Team14,
		team: "Executive",
		facebook: "https://web.facebook.com/",
		linkedin: "https://www.linkedin.com/in/abraham-oluwasegun?trk=contact-info",
    twitter: "https://twitter.com/",
  },
  {
		name: "Muhammad Rabbiat",
		role: "Vice President",
		image: Team9,
		team: "Executive",
		facebook: "https://web.facebook.com/",
		linkedin: "https://www.linkedin.com",
    twitter: "https://twitter.com/",
	},
  {
		name: "Onyilo Jonathan Ojila",
		role: "General Secretary",
		image: Team12,
		team: "Executive",
		facebook: "https://www.facebook.com/jonathan.onyilo.9",
		linkedin: "https://www.linkedin.com",
    twitter: "https://twitter.com/",
	},
  {
		name: "Benjamin Miracle C.",
		role: "Financial Secretary",
		image: Team7,
		team: "Executive",
		facebook: "https://web.facebook.com/",
		linkedin: "https://www.linkedin.com",
    twitter: "https://twitter.com/",
	},
  {
		name: "Obasi Goodness Chidera",
		role: "Treasurer",
		image: Team2,
		team: "Executive",
		facebook: "https://web.facebook.com/",
		linkedin: "https://www.linkedin.com",
    twitter: "https://twitter.com/",
	},
  {
		name: "Attaigu Peter Onimisi",
		role: "Director Of Research & Academics I",
		image: Team11,
		team: "Executive",
		facebook: "https://web.facebook.com/",
		linkedin: "https://www.linkedin.com/in/attaigu-peter-3157791ba?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    twitter: "https://twitter.com/",
	},
  {
		name: "Lamidi Bariu O.",
		role: "Director Of Research II",
		image: Team5,
		team: "Executive",
		facebook: "https://www.facebook.com/lamidi.bariuoj.plusmore?mibextid=ZbWKwL",
		linkedin: "https://www.linkedin.com",
    twitter: "https://www.twitter.com/@bariu_oj",
	},
  {
		name: "Ogunnusi Kolalwole Rapheal",
		role: "Director Of Socials",
		image: Team1,
		team: "Executive",
		facebook: "https://www.facebook.com/kolawole.ogunnusi.27?mibextid=2JQ9oc",
		linkedin: "https://www.linkedin.com",
    twitter: "https://twitter.com/",
	},
  {
		name: "Kayode Abdurasheed Olalekan",
		role: "Director Of Sports",
		image: Team6,
		team: "Executive",
		facebook: "https://www.facebook.com/KhayLhex?mibextid=LQQJ4d",
		linkedin: "https://www.linkedin.com",
    twitter: "https://twitter.com/",
	},
  {
		name: "Oloyede Gbenga Gabriel",
		role: "WelFare Director",
		image: Team3,
		team: "Executive",
		facebook: "https://www.facebook.com/kolawole.ogunnusi.27?mibextid=2JQ9oc",
		linkedin: "https://www.linkedin.com",
    twitter: "https://twitter.com/",
	},
  {
		name: "Ojile Joshua",
		role: "Auditor General",
		image: Team8,
		team: "Executive",
		facebook: "https://web.facebook.com/",
		linkedin: "https://www.linkedin.com",
    twitter: "https://twitter.com/",
	},
  
  {
		name: "Akanmoye Emeka Daniel",
		role: "PRO",
		image: Team4,
		team: "Executive",
		facebook: "https://www.facebook.com/profile.php?id=100091822404435",
		linkedin: "https://www.linkedin.com",
    twitter: "https://twitter.com/",
	},
  {
    name: "Prof Abdullah Idris Enagi",
    role: "HOD Mathematics",
    image: Team15,
    team: "Principal",
    facebook: "https://web.facebook.com/",
    linkedin: "https://www.linkedin.com",
    twitter: "https://twitter.com/",
  },
  {
		name: "Prof. Mohammed Jiya",
		role: "Staff Adviser",
		image: Team13,
		team: "Principal",
		facebook: "https://web.facebook.com/",
		linkedin: "https://www.linkedin.com",
    twitter: "https://twitter.com/",
  },
];
