import Landing from './Landing';
import SignUp from './SignUp';
import SignIn from './SignIn';
import Home from './Home';
import PaymentPage from './PaymentPage';
import Resources from './Resources';
import Profile from './Profile';
import AnnouncementMobile from './AnnouncementMobile';
import NotificationPage from './NotificationPage';
import ErrorPage from './ErrorPage';
import DepartmentalFees from './DepartmentalFees';
import EventsPage from './EventsPage';
import AboutUsPage from './AboutUsPage';
import BlogPage from './BlogPage';
import AdminDashboard from './AdminDashboard';
import AdminPayment from './AdminPayment';
import UserProfile from './UserProfile';
import Comments from './Comments';
import AdminEvents from './AdminEvents';
import AdminAnnouncement from './AdminAnnouncement';
import VerifyUsers from './VerifyUsers';
import VerifyEmail from './VerifyEmail';

export { Landing, SignUp, SignIn, PaymentPage, Home, Resources, Profile, AnnouncementMobile, NotificationPage, ErrorPage, DepartmentalFees, EventsPage, AboutUsPage, BlogPage, AdminDashboard, AdminPayment, UserProfile, Comments, AdminEvents, AdminAnnouncement, VerifyUsers, VerifyEmail };
