import { setCredentials, setPosts, setAnnouncements, setPayments, setCategories, setBlogs, setCurrentPage, setEvents, setNotifications, setUnreadNotificationsCount, logout } from "./slices/authSlice";
import { 
	useLoginMutation,
	useLogoutMutation,
	useRegisterMutation,
	useResetPasswordMutation,
	useSendMailMutation,
	useUpdateUserMutation,
	useGetUserQuery,
	useAllBlogsQuery,
	useVerifyAccountMutation,
	useContactUsMutation,
	useCheckStudentEmailMutation,
} from './slices/usersApiSlice';
import {
	useGetTotalUsersQuery,
	useGetTotalPostsQuery,
	useGetTotalAnnouncementsQuery,
	useGetTotalBlogsQuery,
	useGetTotalPaymentsQuery,
	useGetTotalEventsQuery,
	useGetAllUsersQuery,
	useMakeUserAdminMutation,
	useRemoveAdminMutation,
	useBlockUserMutation,
	useUnblockUserMutation,
	useGetAllPaymentsQuery,
	useCreateBlogMutation,
	useUpdateBlogMutation,
	useDeleteBlogMutation,
	useCreateEventMutation,
	useUpdateEventMutation,
	useDeleteEventMutation,
	useMailNoticeMutation,
	useSendUserMailMutation,
} from './slices/adminApiSlice';
import { 
	useAllPostsQuery,
	useGetFeedQuery,
	usePostQuery,
	usePaginatedPostsQuery,
	useUserPostsQuery,
	useCreatePostMutation,
	useUpdatePostMutation,
	useDeletePostMutation,
	useUpvotePostMutation,
	useDownvotePostMutation,
	useCommentPostMutation,
	usePostCommentsQuery,
	useUpvoteCommentMutation,
	useDownvoteCommentMutation,
	useDeleteCommentMutation,
} from './slices/postSlice';
import {
  useUserBlogsQuery,
  useUpvoteBlogMutation,
  useDownvoteBlogMutation,
  useCommentBlogMutation,
  useUpvoteBlogCommentMutation,
  useDownvoteBlogCommentMutation,
  useDeleteBlogCommentMutation,
} from './slices/blogSlice';

import { 
	useAllCategorysQuery,
	useAllPaymentsQuery,
	useCreateCategoryMutation,
	useCreatePaymentMutation,
	useDeleteCategoryMutation,
	useVerifyPaymentsMutation,
	useUserPaymentsQuery,
	useVerifyUserPaymentsMutation,
	} from './slices/paymentSlice';

import {
	useCreateAnnouncementMutation,
	useAllAnnouncementsQuery,
	useUserAnnouncementsQuery,
	useUpdateAnnouncementMutation,
	useDeleteAnnouncementMutation,
} from './slices/announcementSlice';

import {
	useAllEventsQuery,
} from './slices/eventSlice';

import {
	useGetResourcesQuery,
	useGetResourcesByLevelQuery,
	useSearchQuery,
} from './slices/resourceSlice';

import {
	useGetNotificationsQuery,
	useGetNotificationsPagedQuery,
	useDeleteNotificationMutation,
	useMarkNotificationsAsSeenMutation,
	useClearNotificationsMutation,
} from './slices/notificationApiSlice';

export { 
		useLoginMutation,
		useLogoutMutation, 
		useRegisterMutation,
		useSendMailMutation,
		useUpdateUserMutation,
		useResetPasswordMutation,
		useGetUserQuery,
		useAllPostsQuery,
		useGetFeedQuery,
		usePostQuery,
		usePaginatedPostsQuery,
		useUserPostsQuery,
		useCreatePostMutation,
		useUpdatePostMutation,
		useDeletePostMutation,
		useUpvotePostMutation,
		useDownvotePostMutation,
		usePostCommentsQuery,
		useCommentPostMutation,
		useDeleteCommentMutation,
		useUpvoteCommentMutation,
		useDownvoteCommentMutation,
	useAllBlogsQuery,
	useUserBlogsQuery,
	useCreateBlogMutation,
	useUpdateBlogMutation,
	useDeleteBlogMutation,
	useUpvoteBlogMutation,
	useDownvoteBlogMutation,
	useCommentBlogMutation,
	useUpvoteBlogCommentMutation,
	useDownvoteBlogCommentMutation,
	useDeleteBlogCommentMutation,
	useAllCategorysQuery,
	useAllPaymentsQuery,
	useCreateCategoryMutation,
	useGetAllPaymentsQuery,
	useCreatePaymentMutation,
	useDeleteCategoryMutation,
	useVerifyPaymentsMutation,
	useVerifyUserPaymentsMutation,
	useUserPaymentsQuery,
	useMakeUserAdminMutation,
	useRemoveAdminMutation,
	useBlockUserMutation,
	useUnblockUserMutation,
	useCreateAnnouncementMutation,
	useAllAnnouncementsQuery,
	useUserAnnouncementsQuery,
	useUpdateAnnouncementMutation,
	useDeleteAnnouncementMutation,
	useCreateEventMutation,
	useAllEventsQuery,
	useUpdateEventMutation,
	useDeleteEventMutation,
	useVerifyAccountMutation,
	useGetResourcesQuery,
	useGetResourcesByLevelQuery,
	useSearchQuery,
	useGetTotalUsersQuery,
	useGetTotalPostsQuery,
	useGetTotalAnnouncementsQuery,
	useGetTotalBlogsQuery,
	useGetTotalPaymentsQuery,
	useGetTotalEventsQuery,
  useGetAllUsersQuery,
	useGetNotificationsQuery,
		useGetNotificationsPagedQuery,
	useDeleteNotificationMutation,
	useMarkNotificationsAsSeenMutation,
	useClearNotificationsMutation,
	useContactUsMutation,
	useCheckStudentEmailMutation,
	useMailNoticeMutation,
	useSendUserMailMutation,
	setCredentials,
	setPosts,
	setAnnouncements,
	setPayments,
	setCategories,
	setBlogs,
	setCurrentPage,
	setEvents,
  setNotifications,
	setUnreadNotificationsCount,
	logout,
 }
