import { setCredentials, setPosts } from "./slices/authSlice";
import { 
	useLoginMutation,
	useLogoutMutation,
	useRegisterMutation,
	useUpdateUserMutation,
	useGetUserQuery,
	useMakeUserAdminMutation,
	useRemoveAdminMutation
} from './slices/usersApiSlice';
import { 
	useAllPostsQuery,
	useUserPostsQuery,
	useCreatePostMutation,
	useUpdatePostMutation,
	useDeletePostMutation,
	useUpvotePostMutation,
	useDownvotePostMutation,
	useCommentPostMutation,
	usePostCommentsQuery,
	useUpvoteCommentMutation,
	useDownvoteCommentMutation,
	useDeleteCommentMutation,
} from './slices/postSlice';
import {
  useAllBlogsQuery,
  useUserBlogsQuery,
  useCreateBlogMutation,
  useUpdateBlogMutation,
  useDeleteBlogMutation,
  useUpvoteBlogMutation,
  useDownvoteBlogMutation,
  useCommentBlogMutation,
  useUpvoteBlogCommentMutation,
  useDownvoteBlogCommentMutation,
  useDeleteBlogCommentMutation,
} from './slices/blogSlice';

import { 
	useAllCategorysQuery,
	useAllPaymentsQuery,
	useCreateCategoryMutation,
	useCreatePaymentMutation,
	useDeleteCategoryMutation,
	useVerifyPaymentsMutation,
	} from './slices/paymentSlice'

export { 
		useLoginMutation,
		useLogoutMutation, 
		useRegisterMutation,
		useUpdateUserMutation,
		useGetUserQuery,
		useAllPostsQuery,
		useUserPostsQuery,
		useCreatePostMutation,
		useUpdatePostMutation,
		useDeletePostMutation,
		useUpvotePostMutation,
		useDownvotePostMutation,
		usePostCommentsQuery,
		useCommentPostMutation,
		useDeleteCommentMutation,
		useUpvoteCommentMutation,
		useDownvoteCommentMutation,
	useAllBlogsQuery,
	useUserBlogsQuery,
	useCreateBlogMutation,
	useUpdateBlogMutation,
	useDeleteBlogMutation,
	useUpvoteBlogMutation,
	useDownvoteBlogMutation,
	useCommentBlogMutation,
	useUpvoteBlogCommentMutation,
	useDownvoteBlogCommentMutation,
	useDeleteBlogCommentMutation,
	useAllCategorysQuery,
	useAllPaymentsQuery,
	useCreateCategoryMutation,
	useCreatePaymentMutation,
	useDeleteCategoryMutation,
	useVerifyPaymentsMutation,
	useMakeUserAdminMutation,
	useRemoveAdminMutation,
	setCredentials,
	setPosts, }
